### ISSUE TITLE
no more message.type property make API crash

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1115]
on alpha plaform with the 0.13.0 release:

GET https://alpha.caliopen.org/api/v1/discussions?offset=0&limit=20

```
2018-11-30 14:18:32,613 ERROR [caliopen_api.base.errors][MainThread] Unexpected error Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid_swagger/tween.py", line 187, in validator_tween
    response = handler(request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 156, in handle_request
    view_name
   File "/usr/local/lib/python2.7/dist-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
    response = view_()
   File "/usr/local/lib/python2.7/dist-packages/caliopen_api/message/discussion.py", line 30, in collection_get
    offset=self.get_offset())
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/core/discussion.py", line 118, in get
    return {'discussions': list(responses), 'total': total}
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/core/discussion.py", line 109, in build_responses
    yield build_discussion(core, discussion)
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/core/discussion.py", line 73, in build_discussion
    discuss.protocol = index.last_message.type
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 128, in __getattr__
    return super(DocType, self).__getattr__(name)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/utils.py", line 336, in __getattr__
    return super(ObjectBase, self).__getattr__(name)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/utils.py", line 115, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
 AttributeError: 'IndexedMessage' object has no attribute 'type'
: 500 Internal Server Error
```

**Comment by sapiens-sapide** [comment]
should be fixed by commit #c46f2791 on master
