### ISSUE TITLE
password reset mail does not work

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1124]
On release 0.13 (and may be 0.12 one) the reset password mail is not sent

apiv2
-----

```
<daemon.info> Dec  4 15:15:37 api1 caliopen_rest[30978]: time="2018-12-04T15:15:37+01:00" level=info msg="[RESTFacility] reset password session deleted for user <xxx> [15187997-c3b5-4a1e-a3ae-02bb58663611]"
<daemon.info> Dec  4 15:15:37 api1 caliopen_rest[30978]: time="2018-12-04T15:15:37+01:00" level=info msg="[RESTFacility] reset password session ignited for user <xxx> [15187997-c3b5-4a1e-a3ae-02bb58663611]"
<daemon.info> Dec  4 15:15:37 api1 caliopen_rest[30978]: [GIN] 2018/12/04 - 15:15:37 | 204 |   17.724565ms |   192.168.1.100 | POST     /api/v2/passwords/reset
<daemon.info> Dec  4 15:16:08 api1 caliopen_rest[30978]: time="2018-12-04T15:16:08+01:00" level=warning msg="[RESTfacility] sending password reset email failed for user 15187997-c3b5-4a1e-a3ae-02bb58663611" error="nats: timeout"
```

nats
----

```
[23174] 2018/12/04 15:21:36.552366 [TRC] 192.168.1.100:50506 - cid:9 - ->> [PUB outboundSMTP _INBOX.0Ia9jGoEKqPxc5XbbcHKFH.0Ia9jGoEKqPxc5XbbcHMZo 135]
[23174] 2018/12/04 15:21:36.552467 [TRC] 192.168.1.100:50506 - cid:9 - ->> MSG_PAYLOAD: [{"message_id":"5e46c851-ff19-4ad2-b643-db8ba05785a0","order":"deliver","remote_id":"","user_id":"ded68234-613c-4d97-b135-958d8bc3eb8a"}]
[23174] 2018/12/04 15:21:36.552594 [TRC] 192.168.1.136:39072 - cid:1 - <<- [MSG outboundSMTP 2 _INBOX.0Ia9jGoEKqPxc5XbbcHKFH.0Ia9jGoEKqPxc5XbbcHMZo 135]
```

lmtp
----

```
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: panic: runtime error: index out of range
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: goroutine 143 [running]:
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).natsMsgHandler(0xc000eca480, 0xc000f9be00, 0xc000038f60, 0x46cf98, 0xc000eaa600, 0x0, 0x1fd2a0)
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: /home/mric/dev/caliopen/go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/outbound.go:95 +0x1421
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).startOutcomingSmtpAgents.func1(0xc000f9be00)
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: /home/mric/dev/caliopen/go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/outbound.go:32 +0x38
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: github.com/CaliOpen/Caliopen/src/backend/vendor/github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc0000c8000, 0xc000eaa600)
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: /home/mric/dev/caliopen/go/src/github.com/CaliOpen/Caliopen/src/backend/vendor/github.com/nats-io/go-nats/nats.go:1702 +0x227
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: created by github.com/CaliOpen/Caliopen/src/backend/vendor/github.com/nats-io/go-nats.(*Conn).subscribe
Dec 04 15:31:34 lmtp1 caliopen_lmtpd[10005]: /home/mric/dev/caliopen/go/src/github.com/CaliOpen/Caliopen/src/backend/vendor/github.com/nats-io/go-nats/nats.go:2424 +0x446

```

outbound.go l95
---------------

```
//checks if identity is local or remote
//fetch credentials and remote server info accordingly
firstIdentity, err := b.Store.RetrieveUserIdentity(m.User_id.String(), m.UserIdentities[0].String(), true) // handle one identity only for now
```

message interesting information
-------------------------------

```
cqlsh:caliopen> select user_identities from message  where message_id  = 4edc7825-e35e-42bf-b33d-0c546d50e52a;

            null
```

so the fact that message is created without user identity, make the process fail when it try to resolve this identity

**Comment by sapiens-sapide** [comment]
should be fixed by commit #eee6ae6b
