### ISSUE TITLE
Elasticsearch fail to query discussion

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1129]
Found many backtrace on api1.alpha machine with an elasticsearch error that must be investigate:

```
2018-12-06 17:04:25,612 DEBUG [elasticsearch][MainThread] < {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [discussion_id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"141cdb82-7950-46ad-a046-55469067a1fa","node":"l2FajsBzQhWKbO1TZJR4KA","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [discussion_id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
2018-12-06 17:04:25,621 ERROR [caliopen_api.base.errors][MainThread] Unexpected error Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid_swagger/tween.py", line 187, in validator_tween
    response = handler(request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 156, in handle_request
    view_name
   File "/usr/local/lib/python2.7/dist-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
   File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
    response = view_()
   File "/usr/local/lib/python2.7/dist-packages/caliopen_api/message/discussion.py", line 30, in collection_get
    offset=self.get_offset())
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/core/discussion.py", line 116, in get
    min_il=min_il, max_il=max_il)
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/store/discussion_index.py", line 91, in list_discussions
    max_il)
   File "/usr/local/lib/python2.7/dist-packages/caliopen_main/discussion/store/discussion_index.py", line 57, in __search_ids
    result = search.execute()
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/search.py", line 606, in execute
    **self._params
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
 RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [discussion_id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')
: 500 Internal Server Error^M
Content-Length: 272^M
Content-Type: application/json; charset=UTF-8^M
^M
{"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "collection_discussion", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
```

**Comment by sapiens-sapide** [comment]
strange, it looks like incorrect mapping… because `discussion_id` is already a _keyword_ in our mapping definition
