### ISSUE TITLE
err 500 on /me - associated contact: Value must be one of [u'work', u'home', u'other'].

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1179]
```
apiv1_1            | ERROR:caliopen_api.base.errors:Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween                                                                      
apiv1_1            |     response = handler(request)                                                                                                                                    
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid_swagger/tween.py", line 193, in validator_tween                                                            
apiv1_1            |     response = handler(request)                                                                                                                                    
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request                                                                    
apiv1_1            |     registry, request, context, context_iface, view_name              
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/view.py", line 657, in _call_view                                                                          
apiv1_1            |     response = view_callable(context, request)                                                                                                                     
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in __call__                                                                    
apiv1_1            |     return view(context, request)                                                                                                                                  
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 325, in secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/user/user.py", line 230, in get
apiv1_1            |     return ReturnUser.build(user).serialize()
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.storage/caliopen_storage/parameters.py", line 90, in build
apiv1_1            |     obj.validate()
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/schematics/models.py", line 258, in validate
apiv1_1            |     partial=partial, convert=convert, app_data=app_data, **kwargs)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/schematics/models.py", line 299, in _convert
apiv1_1            |     return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
apiv1_1            |    File "/usr/local/lib/python2.7/site-packages/schematics/validate.py", line 67, in validate
apiv1_1            |     raise DataError(errors, data)
apiv1_1            |  DataError: {"contact": {"emails": {"0": {"type": ["Value must be one of [u'work', u'home', u'other']."]}}}}
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 257
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            |
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "MeUser", "values": 500,
 "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
apiv1_1            | [pid: 36|app: 0|req: 53/155] 172.18.0.14 () {60 vars in 2132 bytes} [Mon Jan 14 14:16:27 2019] GET /api/v1/me => generated 257 bytes in 203 msecs (HTTP/1.0 500) 2 h
eaders in 106 bytes (1 switches on core 0)
```

**Comment by gdchamal** [comment]
should be fixed by https://github.com/CaliOpen/Caliopen/commit/83b77796020ef8fd5ae4f3f0ed3a9cf5bed3ee82
