### ISSUE TITLE
imap-worker crash on alpha platform

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1202]
The imap worker crash on alpha platform after a long run with this error :

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 93076 [running]:
github.com/CaliOpen/Caliopen/src/backend/protocols/go%2eimap.buildXheaders(0xc446e3b880, 0xc420fd0dc0, 0xc421646940, 0xc423804a00, 0x0, 0xd92820, 0x5, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/CaliOpen/Caliopen/src/backend/protocols/go.imap/imap.go:230 +0xc3c
github.com/CaliOpen/Caliopen/src/backend/protocols/go%2eimap.(*Fetcher).syncMails(0xc42220d3b0, 0xc420fd0dc0, 0xc421646940, 0xc42116e300, 0x0, 0x0)
	/go/src/github.com/CaliOpen/Caliopen/src/backend/protocols/go.imap/fetcher.go:265 +0x3f2
created by github.com/CaliOpen/Caliopen/src/backend/protocols/go%2eimap.(*Fetcher).SyncRemoteWithLocal
	/go/src/github.com/CaliOpen/Caliopen/src/backend/protocols/go.imap/fetcher.go:105 +0x56c
```

**Comment by sapiens-sapide** [comment]
Fix in master, commit #0318c646
