### ISSUE TITLE
imapworker crash

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1321]
```
imapworker_1      | time="2019-05-09T09:37:54Z" level=info msg="natsMessage: {\"order\":\"process_raw\",\"user_id\":\"f58af3a6-2a23-4f1b-8779-4d763e7d01bd\",\"identity_id\":\"73cf8734-52f9-4d5c-8320-11bfa17507d7\",\"message_id\": \"7caad08f-808c-4c18-919a-f62180c24f86\"}\nnatsResponse: &{_INBOX.9Sh4Fzh5fDQzTScKs3XTlp.9Sh4Fzh5fDQzTScKs3XYKt  {\"message\": \"inbound email message process failed\", \"error\": \"'ascii' codec can't decode byte 0xc3 in position 95: ordinal not in range(128)\"} %!s(*nats.Subscription=&{{0 0} 1 _INBOX.9Sh4Fzh5fDQzTScKs3XTlp.*  77 0 0xc420d1e000 0xaee390 <nil> false false false 0 <nil> <nil> 0xc420fdf440 0 0 1 143 65536 67108864 0}) %!s(*nats.Msg=<nil>) %!s(*nats.barrierInfo=<nil>)}\n"
imapworker_1      | panic: send on closed channel
imapworker_1      | 
imapworker_1      | goroutine 1706 [running]:
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInbound.func1(0xc4202e24a0, 0xc4202e2520)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:157 +0x43
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInbound(0xc420c6cd80, 0xc421761fa8, 0x1, 0x1, 0xc4202e24a0, 0x1, 0xc4202e2520)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:250 +0x455
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInboundIMAP(0xc420c6cd80, 0xc4202e24a0)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:144 +0x20a
imapworker_1      | created by github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).imapWorker
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:86 +0x64
```

**Comment by gdchamal** [comment]
Fix in #1319
