### ISSUE TITLE
imap worker crash after sync w/ my mailbox

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#1336]
```
imapworker_1      | time="2019-05-11T12:12:39Z" level=info msg="EmailBroker : NATS inbound request successfully handled for user 33a51dbd-07e5-4673-b70f-992df23f184a : OK : inbound email message proceeded"
imapworker_1      | panic: send on closed channel
imapworker_1      | 
imapworker_1      | goroutine 3451 [running]:
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInbound.func1(0xc42076ae00, 0xc42076ae60)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:157 +0x43
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInbound(0xc4203c8d80, 0xc4213d7fa8, 0x1, 0x1, 0xc42076ae00, 0xc4207a4701, 0xc42076ae60)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:256 +0x4c2
imapworker_1      | github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).processInboundIMAP(0xc4203c8d80, 0xc42076ae00)
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:144 +0x20a
imapworker_1      | created by github.com/CaliOpen/Caliopen/src/backend/brokers/go%2eemails.(*EmailBroker).imapWorker
imapworker_1      |     /go/src/github.com/CaliOpen/Caliopen/src/backend/brokers/go.emails/inbound.go:86 +0x64
```

I have 615 message in inbox and it has synced 27 discussions (no clue on how many messages are missing).

It looks like I can't get the message I receive from my protonmail account

**Comment by iamdey** [comment]
it happened on my instance not the deployed one
