### ISSUE TITLE
delivery fail with bad participant value

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1367]
Found many backtrace in mq-worker logs :
```
[mq-worker-6ddc9b954f-nxjzl] Traceback (most recent call last): 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/subscribers.py", line 46, in process_raw 
[mq-worker-6ddc9b954f-nxjzl]     new_message = deliver.process_raw(payload['message_id']) 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/delivery.py", line 37, in process_raw 
[mq-worker-6ddc9b954f-nxjzl]     message = self.qualifier.process_inbound(raw) 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/components/py.pi/caliopen_pi/qualifiers/mail.py", line 142, in process_inbound 
[mq-worker-6ddc9b954f-nxjzl]     new_message) 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/components/py.pi/caliopen_pi/qualifiers/mail.py", line 69, in lookup_discussion_sequence 
[mq-worker-6ddc9b954f-nxjzl]     seq.append(('hash', message.hash_participants)) 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/main/py.main/caliopen_main/message/parameters/message.py", line 62, in hash_participants 
[mq-worker-6ddc9b954f-nxjzl]     ids_hash = hash_participants_uri(self.participants) 
[mq-worker-6ddc9b954f-nxjzl]   File "/srv/caliopen/src/backend/main/py.main/caliopen_main/participant/core/participant.py", line 40, in hash_participants_uri 
[mq-worker-6ddc9b954f-nxjzl]     raise Exception("missing mandatory property in participant") 
[mq-worker-6ddc9b954f-nxjzl] Exception: missing mandatory property in participant 
[mq-worker-6ddc9b954f-nxjzl] ERROR:subscribers:deliver process failed for raw {u'message_id': u'80d28fea-09de-41dd-9ca6-690a2f1a4e6d', u'user_id': u'bd9e7f6d-2e11-4f64-a317-66d8399b0de9', u'order': u'process_raw', u'identity_id': u'3c5ca8a9-9f67-4771-94eb-43eed8be6c1d'}: None 
```

**Comment by gdchamal** [comment]
Parsing of email failed stupidly when a ',' is present in the "name" part of a From

**Comment by gdchamal** [comment]
Fixed with https://github.com/CaliOpen/Caliopen/commit/dfdad14d3b3b1e129a4ac742db2a7bf72648af53
