### ISSUE TITLE
Inbound message_id is missing ?

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1385]
Found on production now :

```
[mq-worker-6f595b4dc6-s2x82] ERROR:caliopen_main.message.parsers.mail:Unable to find correct message_id None 
[mq-worker-6f595b4dc6-s2x82] Traceback (most recent call last): 
[mq-worker-6f595b4dc6-s2x82]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/subscribers.py", line 46, in process_raw 
[mq-worker-6f595b4dc6-s2x82]     new_message = deliver.process_raw(payload['message_id']) 
[mq-worker-6f595b4dc6-s2x82]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/delivery.py", line 40, in process_raw 
[mq-worker-6f595b4dc6-s2x82]     external_msg_id=message.external_msg_id) 
[mq-worker-6f595b4dc6-s2x82]   File "/srv/caliopen/src/backend/main/py.storage/caliopen_storage/store/model.py", line 50, in filter 
[mq-worker-6f595b4dc6-s2x82]     return cls.objects.filter(**kwargs) 
[mq-worker-6f595b4dc6-s2x82]   File "/usr/local/lib/python2.7/site-packages/cassandra/cqlengine/query.py", line 594, in filter 
[mq-worker-6f595b4dc6-s2x82]     raise CQLEngineException("None values on filter are not allowed") 
[mq-worker-6f595b4dc6-s2x82] CQLEngineException: None values on filter are not allowed 
[mq-worker-6f595b4dc6-s2x82] ERROR:subscribers:deliver process failed for raw {u'message_id': u'05e65821-595f-4992-8a3b-d9ab4e486f43', u'user_id': u'2caeaba7-3233-4038-aa83-474377ddfaee', u'order': u'process_raw', u'identity_id': u'a8f55cdb-d359-4b82-9c81-797b512f911b'}
```

**Comment by gdchamal** [comment]
Fixed with #d16166da4
