### ISSUE TITLE
Encoding and formatting problems of the moment

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#1388]
Some mail don't have a valid `Date:` header

```
[mq-worker-564d54ccf-h5tld] Traceback (most recent call last): 
[imap-worker-54d74c9b6b-2z9hr] time="2019-05-22T11:10:18Z" level=warning msg="[EmailBroker] inbound delivery failed for user ab3f50c9-6199-4d6e-a3ae-7493133049b9" error="'NoneType' object has no attribute '__getitem__'" 
[mq-worker-564d54ccf-h5tld]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/subscribers.py", line 46, in process_raw 
[mq-worker-564d54ccf-h5tld]     new_message = deliver.process_raw(payload['message_id']) 
[mq-worker-564d54ccf-h5tld]   File "/srv/caliopen/src/backend/interfaces/NATS/py.client/caliopen_nats/delivery.py", line 36, in process_raw 
[mq-worker-564d54ccf-h5tld]     message = self.qualifier.process_inbound(raw) 
[mq-worker-564d54ccf-h5tld]   File "/srv/caliopen/src/backend/components/py.pi/caliopen_pi/qualifiers/mail.py", line 94, in process_inbound 
[mq-worker-564d54ccf-h5tld]     new_message.date = email.date 
[mq-worker-564d54ccf-h5tld]   File "/srv/caliopen/src/backend/main/py.main/caliopen_main/message/parsers/mail.py", line 259, in date 
[mq-worker-564d54ccf-h5tld]     return datetime.datetime.fromtimestamp(mktime_tz(tmp_date)) 
[mq-worker-564d54ccf-h5tld]   File "/usr/local/lib/python2.7/email/_parseaddr.py", line 154, in mktime_tz 
[mq-worker-564d54ccf-h5tld]     if data[9] is None: 
[mq-worker-564d54ccf-h5tld] TypeError: 'NoneType' object has no attribute '__getitem__' 
[mq-worker-564d54ccf-h5tld] ERROR:subscribers:deliver process failed for raw {u'message_id': u'88808663-16b7-490e-b819-f6d4d290b8d4', u'user_id': u'ab3f50c9-6199-4d6e-a3ae-7493133049b9', u'order': u'process_raw', u'identity_id': u'3e81a947-5f1a-4f57-aa44-926962af8557'}: None 
```
Inspecting the message I found this header value :

```
n [7]: mail.mail['Date']
Out[7]: '[Dtae]'
```

**Comment by gdchamal** [comment]
Filename encoding is not processed correctly :

```
    ...: import logging
    ...: from caliopen_main.user.core import User, UserIdentity
    ...: from caliopen_main.message.core import RawMessage
    ...: from caliopen_main.message.parsers.mail import MailMessage
    ...: from caliopen_pi.qualifiers import UserMessageQualifier
    ...: 
    ...: 
    ...: logging.basicConfig(level=logging.INFO)
    ...: data = {u'message_id': u'75baad05-6071-41e2-81bd-de3a6c1c582d', u'user_id': u'ab3f50c9-6199-4d6e-a3ae-7493133049b9', u'order':
    ...:  u'process_raw', u'identity_id': u'3e81a947-5f1a-4f57-aa44-926962af8557'}
    ...: 
    ...: user_id = data['user_id']
    ...: raw_id = data['message_id']
    ...: raw = RawMessage.get(raw_id)
    ...: mail = MailMessage(raw.raw_data)
    ...: 
    ...: 
    ...: user = User.get(user_id)
    ...: 
    ...: 
    ...: class Identity(object):
    ...: 
    ...:     def __init__(self):
    ...:         self.identifier = ''
    ...:         self.protocol = ''
    ...: 
    ...: identity_id = data['identity_id']
    ...: ident = UserIdentity.get(user, identity_id)
    ...: 
    ...: 
    ...: qual = UserMessageQualifier(user, ident)
    ...: message = qual.process_inbound(raw)
    ...: 
WARNING:caliopen_main.message.parsers.mail:Invalid filename encoding
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/opt/Caliopen/src/backend/tools/py.CLI/caliopen_cli/commands/shell.pyc in <module>()
     30 
     31 qual = UserMessageQualifier(user, ident)
---> 32 message = qual.process_inbound(raw)

/opt/Caliopen/src/backend/components/py.pi/caliopen_pi/qualifiers/mail.pyc in process_inbound(self, raw)
    118                 raw.raw_msg_id))
    119 
--> 120         for a in email.attachments:
    121             attachment = Attachment()
    122             attachment.content_type = a.content_type

/opt/Caliopen/src/backend/main/py.main/caliopen_main/message/parsers/mail.pyc in attachments(self)
    298                     continue
    299                 if MailAttachment.is_attachment(p):
--> 300                     attchs.append(MailAttachment(p))
    301         return attchs
    302 

/opt/Caliopen/src/backend/main/py.main/caliopen_main/message/parsers/mail.pyc in __init__(self, part)
     46             except UnicodeError:
     47                 log.warn('Invalid filename encoding')
---> 48                 self.filename = self.filename.decode('utf-8', errors='ignore')
     49         content_disposition = part.get("Content-Disposition")
     50         if content_disposition:

/opt/Caliopen/.venv/lib/python2.7/encodings/utf_8.pyc in decode(input, errors)
     14 
     15 def decode(input, errors='strict'):
---> 16     return codecs.utf_8_decode(input, errors, True)
     17 
     18 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 5: ordinal not in range(128)

In [24]: p1.get_filename()
Out[24]: u'Mise \xe0 disposition de services en ligne.pdf'

```
