### ISSUE TITLE
[API] Error with locales generation on Docker images build

### ISSUE THREAD

**Issue by Branlala** [CaliOpen/Caliopen#15]
I had to modify api/Dockerfile to avoid the following error :
```
Step 12 : RUN pip install bcrypt
 ---> Running in 340601996f5d
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
ERROR: Service 'api' failed to build: The command '/bin/sh -c pip install bcrypt' returned a non-zero code: 1
```

Here is the Dockerfile I used :
```
Step 12 : RUN pip install bcrypt
 ---> Running in 340601996f5d
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
ERROR: Service 'api' failed to build: The command '/bin/sh -c pip install bcrypt' returned a non-zero code: 1


```

**Comment by iamdey** [comment]
yes, it is already fixed but not merged yet : https://github.com/CaliOpen/caliopen.api/pull/4
It will be reviewed and merged by @gdchamal as soon as he comes back (about 2 weeks).

PS: You're very welcome to review any PR for Caliopen ;) (those 2 PR may interest you: https://github.com/CaliOpen/caliopen.api/pull/5 and https://github.com/CaliOpen/caliopen-dev/pull/48)

**Comment by Branlala** [comment]
Thanks a lot, I'll have a look a that :-)

PS : I had to do the same fix in file cli/Dockerfile ;-)

**Comment by iamdey** [comment]
oh nice catch, feel free to open a PR.

**Comment by iamdey** [comment]
* [x] CaliOpen/caliopen.api#/4 
* [ ] CaliOpen/caliopen.cli
