### ISSUE TITLE
NPM error on web-client-ng start

### ISSUE THREAD

**Issue by ncoden** [CaliOpen/Caliopen#16]
Errors which don't prevent docker to start and work, but it make NPM try to rebuild on each start, and generate lot of logs :/

Full log: https://gist.github.com/ncoden/1574df10f77da6e233455976b7735685

Usefull portions:

```
web-client-ng_1 | npm info install fsevents@1.0.11
web-client-ng_1 |
web-client-ng_1 | > fsevents@1.0.11 install /usr/share/caliopen/web-client-ng/node_modules/fsevents
web-client-ng_1 | > node-pre-gyp install --fallback-to-build
web-client-ng_1 |
web-client-ng_1 | node-pre-gyp info it worked if it ends with ok
web-client-ng_1 | node-pre-gyp info using node-pre-gyp@0.6.25
web-client-ng_1 | node-pre-gyp info using node@4.2.4 | linux | x64
web-client-ng_1 | node-pre-gyp info check checked for "/usr/share/caliopen/web-client-ng/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64/fse.node" (not found)
web-client-ng_1 | node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.11/fse-v1.0.11-node-v46-linux-x64.tar.gz
web-client-ng_1 | node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.11/fse-v1.0.11-node-v46-linux-x64.tar.gz
web-client-ng_1 | node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.11/fse-v1.0.11-node-v46-linux-x64.tar.gz (falling back to source compile with node-gyp)
web-client-ng_1 | gyp info it worked if it ends with ok
web-client-ng_1 | gyp info using node-gyp@3.0.3
web-client-ng_1 | gyp info using node@4.2.4 | linux | x64
web-client-ng_1 | gyp info ok
web-client-ng_1 | gyp info it worked if it ends with ok
web-client-ng_1 | gyp info using node-gyp@3.0.3
web-client-ng_1 | gyp info using node@4.2.4 | linux | x64
web-client-ng_1 | gyp info spawn python2
web-client-ng_1 | gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
web-client-ng_1 | gyp info spawn args   'binding.gyp',
web-client-ng_1 | gyp info spawn args   '-f',
web-client-ng_1 | gyp info spawn args   'make',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/usr/share/caliopen/web-client-ng/node_modules/fsevents/build/config.gypi',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/root/.node-gyp/4.2.4/include/node/common.gypi',
web-client-ng_1 | gyp info spawn args   '-Dlibrary=shared_library',
web-client-ng_1 | gyp info spawn args   '-Dvisibility=default',
web-client-ng_1 | gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.4',
web-client-ng_1 | gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
web-client-ng_1 | gyp info spawn args   '-Dnode_lib_file=node.lib',
web-client-ng_1 | gyp info spawn args   '-Dmodule_root_dir=/usr/share/caliopen/web-client-ng/node_modules/fsevents',
web-client-ng_1 | gyp info spawn args   '--depth=.',
web-client-ng_1 | gyp info spawn args   '--no-parallel',
web-client-ng_1 | gyp info spawn args   '--generator-output',
web-client-ng_1 | gyp info spawn args   'build',
web-client-ng_1 | gyp info spawn args   '-Goutput_dir=.' ]
web-client-ng_1 | gyp info ok
web-client-ng_1 | gyp info it worked if it ends with ok
web-client-ng_1 | gyp info using node-gyp@3.0.3
web-client-ng_1 | gyp info using node@4.2.4 | linux | x64
web-client-ng_1 | gyp info spawn make
web-client-ng_1 | gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
web-client-ng_1 | make: Entering directory '/usr/share/caliopen/web-client-ng/node_modules/fsevents/build'
web-client-ng_1 |   SOLINK_MODULE(target) Release/obj.target/.node
web-client-ng_1 |   COPY Release/.node
web-client-ng_1 | make: Leaving directory '/usr/share/caliopen/web-client-ng/node_modules/fsevents/build'
web-client-ng_1 | gyp info ok
web-client-ng_1 | node-pre-gyp info ok
web-client-ng_1 | npm info postinstall fsevents@1.0.11
```

```
web-client-ng_1 | npm info install node-sass@2.1.1
web-client-ng_1 |
web-client-ng_1 | > node-sass@2.1.1 install /usr/share/caliopen/web-client-ng/node_modules/node-sass
web-client-ng_1 | > node scripts/install.js
web-client-ng_1 |
web-client-ng_1 | npm info postinstall node-sass@2.1.1
web-client-ng_1 |
web-client-ng_1 | > node-sass@2.1.1 postinstall /usr/share/caliopen/web-client-ng/node_modules/node-sass
web-client-ng_1 | > node scripts/build.js
web-client-ng_1 |
web-client-ng_1 | gyp info it worked if it ends with ok
web-client-ng_1 | gyp info using pangyp@2.3.3
web-client-ng_1 | gyp info using node@4.2.4 | linux | x64
web-client-ng_1 | gyp info spawn python
web-client-ng_1 | gyp info spawn args [ '/usr/share/caliopen/web-client-ng/node_modules/node-sass/node_modules/pangyp/gyp/gyp_main.py',
web-client-ng_1 | gyp info spawn args   'binding.gyp',
web-client-ng_1 | gyp info spawn args   '-f',
web-client-ng_1 | gyp info spawn args   'make',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/usr/share/caliopen/web-client-ng/node_modules/node-sass/build/config.gypi',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/usr/share/caliopen/web-client-ng/node_modules/node-sass/node_modules/pangyp/addon.gypi',
web-client-ng_1 | gyp info spawn args   '-I',
web-client-ng_1 | gyp info spawn args   '/root/.node-gyp/4.2.4/common.gypi',
web-client-ng_1 | gyp info spawn args   '-Dlibrary=shared_library',
web-client-ng_1 | gyp info spawn args   '-Dvisibility=default',
web-client-ng_1 | gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.4',
web-client-ng_1 | gyp info spawn args   '-Druntime=node',
web-client-ng_1 | gyp info spawn args   '-Dmodule_root_dir=/usr/share/caliopen/web-client-ng/node_modules/node-sass',
web-client-ng_1 | gyp info spawn args   '--depth=.',
web-client-ng_1 | gyp info spawn args   '--no-parallel',
web-client-ng_1 | gyp info spawn args   '--generator-output',
web-client-ng_1 | gyp info spawn args   'build',
web-client-ng_1 | gyp info spawn args   '-Goutput_dir=.' ]
web-client-ng_1 | gyp: /root/.node-gyp/4.2.4/common.gypi not found (cwd: /usr/share/caliopen/web-client-ng/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
web-client-ng_1 | gyp ERR! configure error
web-client-ng_1 | gyp ERR! stack Error: `gyp` failed with exit code: 1
web-client-ng_1 | gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/caliopen/web-client-ng/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
web-client-ng_1 | gyp ERR! stack     at emitTwo (events.js:87:13)
web-client-ng_1 | gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
web-client-ng_1 | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
web-client-ng_1 | gyp ERR! System Linux 4.1.18-boot2docker
web-client-ng_1 | gyp ERR! command "/usr/local/bin/node" "/usr/share/caliopen/web-client-ng/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
web-client-ng_1 | gyp ERR! cwd /usr/share/caliopen/web-client-ng/node_modules/node-sass
web-client-ng_1 | gyp ERR! node -v v4.2.4
web-client-ng_1 | gyp ERR! pangyp -v v2.3.3
web-client-ng_1 | gyp ERR! not ok
web-client-ng_1 | Build failed
```

poke @iamdey

**Comment by iamdey** [comment]
on the gist I see `web-client-ng_1 | > gulp build watch` so your container is working finally, isn't it ?

**Comment by ncoden** [comment]
As said, yes container work
> Errors which don't prevent docker to start and work, but it make NPM try to rebuild on each start, and generate lot of logs :/

**Comment by iamdey** [comment]
oups didn't saw `don't` 

so there is no bug

**Comment by ncoden** [comment]
"help wanted". Aie
