### ISSUE TITLE
use subcontact (contact details) id to (C)RUD

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#18]
I can't delete an email (or I didn't understand how to) since the action requires an address that is not provided by the path, see https://github.com/CaliOpen/caliopen.api.user/blob/abded84cf516247f7ae93d37e7e8c536aebea59b/caliopen/api/user/contact.py#L191-L211

So when I DELETE `/api/v1/contacts/{id}/emails/{name@domain.tld}` it fails with an error 400

---

It could be simplier to use subcontact id for that kind of operations, so the api should give it on GET calls.

What do you think ?

(Also we'll need UPDATE method in order to set is_primary or label after creation ... or we drop those notions)

**Comment by gdchamal** [comment]
in fact depending on subcontact object, the key is the object value.

address for email or im
number for phone

Some objects that can't have a natural key (postal address) have in such case an uuid as key.

**Comment by iamdey** [comment]
well, I still not get how to DELETE a subcontact object. Can you provide an url and eventual body request as example ?

**Comment by gdchamal** [comment]
Fixed for emails and ims sub object with commit https://github.com/CaliOpen/caliopen.api.user/commit/9ec6a8a46159f47bb00da90a620a9eef84ebcd37

**Comment by iamdey** [comment]
Ok with email but it fails with IM:

```
api_1           | 2016-04-27 08:59:02,425 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/757c276b-9505-4e1e-9a28-74150fe8fd50/ims/foo@bar.tld
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 392, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1           |     response = view(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1           |     response = view_()
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 259, in delete
api_1           |     res = self._delete(address, 'delete_im')
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 116, in _delete
api_1           |     return getattr(contact, delete_func)(relation_id)
api_1           |   File "/srv/caliopen/src/caliopen.base.user/caliopen/base/user/core/contact.py", line 293, in delete_im
api_1           |     return self._delete_relation('ims', im_addr)
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/core/mixin.py", line 78, in _delete_relation
api_1           |     lookup = lookupkls.get(self.user, id)
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/core/base.py", line 129, in get
api_1           |     obj = cls._model_class.get(user_id=user.user_id, **param)
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/store/model.py", line 39, in get
api_1           |     raise NotFound(exc)
api_1           | NotFound
web_1           | DELETE /api/v1/contacts/757c276b-9505-4e1e-9a28-74150fe8fd50/ims/foo@bar.tld 500 81.043 ms - 110
```

**Comment by iamdey** [comment]
Ok, it's another pbm. all things works as expected (except it should return a 404 error)
