### ISSUE TITLE
cli mails import fails

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#20]
List of Errors TraceBack  for mails importation

**Comment by iamdey** [comment]
When I import my arcives for 2015:

cli command says:

```
/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py:1356: UserWarning: 'create' and 'save' actions on Counters are deprecated. A future version will disallow this. Use the 'update' mechanism instead.
  warn("'create' and 'save' actions on Counters are deprecated. A future version will disallow this. Use the 'update' mechanism instead.")
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/srv/caliopen/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/srv/caliopen/cli/caliopen/cli/commands/import_email.py", line 80, in import_email
    res = agent.process(mailfrom, rcpts, msg.mail.as_string())
  File "/srv/caliopen/src/caliopen.smtp/caliopen/smtp/agent.py", line 74, in process
    raw = RawMessage.create(user, message_id, buf)
  File "/srv/caliopen/src/caliopen.base.message/caliopen/base/message/core/raw.py", line 29, in create
    data=raw)
  File "/srv/caliopen/src/caliopen.base/caliopen/base/core/base.py", line 59, in create
    obj = cls._model_class.create(**kwargs)
  File "/srv/caliopen/src/caliopen.base/caliopen/base/store/model.py", line 31, in create
    return super(BaseModel, cls).create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/models.py", line 623, in create
    return cls.objects.create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 885, in create
    .if_exists(self._if_exists) \
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/models.py", line 689, in save
    if_exists=self._if_exists).save()
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1379, in save
    self._execute(insert)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1235, in _execute
    tmp = connection.execute(q, consistency_level=self._consistency, timeout=self._timeout)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/connection.py", line 173, in execute
    result = session.execute(query, params, timeout=timeout)
  File "cassandra/cluster.py", line 1581, in cassandra.cluster.Session.execute (cassandra/cluster.c:27046)
  File "cassandra/cluster.py", line 3145, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:59905)
cassandra.WriteFailure: code=1500 [Replica(s) failed to execute write] message="Operation failed - received 0 responses and 1 failures" info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```

cassandra says: 

```
cassandra_1     | ERROR 09:41:09 Failed to apply mutation locally : {}
cassandra_1     | java.lang.IllegalArgumentException: Mutation of 17902080 bytes is too large for the maxiumum size of 16777216
cassandra_1     |       at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:264) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:469) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:384) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:202) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.db.Mutation.apply(Mutation.java:214) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.db.Mutation.apply(Mutation.java:228) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1333) ~[apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2498) [apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72-internal]
cassandra_1     |       at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:136) [apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-3.3.jar:3.3]
cassandra_1     |       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
```

Actually I don't witch case is not supported

**Comment by gdchamal** [comment]
not reproduced, may a version of cassandra or the container not working properly

This kind of error should occur with a real cluster not a single cassandra ring
