### ISSUE TITLE
Err 500 when loosing authentication

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#21]
After a moment, `caliopen.api` loose the authentication but not `caliopen.web` and so:

```
api_1           | 2016-04-22 15:12:56,498 ERROR [waitress][waitress] Exception when serving /api/v1/contacts
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 392, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 243, in _secured_view
api_1           |     result = _permitted(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 239, in _permitted
api_1           |     principals = self.authn_policy.effective_principals(request)
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/authentication.py", line 79, in effective_principals
api_1           |     account = self.authenticated_userid(request)
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/authentication.py", line 72, in authenticated_userid
api_1           |     request._CaliopenUser = AuthenticatedUser(request)
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/authentication.py", line 38, in __init__
api_1           |     if infos.get('access_token') != token:
api_1           | AttributeError: 'NoneType' object has no attribute 'get'
web_1           | GET /api/v1/contacts 500 7.817 ms - 110
```

**Comment by gdchamal** [comment]
until we implement a refresh token API, we may increase token TTL in api/development.ini

Currently it's 3600 seconds:

kvs.cache = {"kvs": "redis",
             "ttl": 3600,
             "kvs_kwargs": {"host": "redis.dev.caliopen.org"},
             "key_prefix": "tokens::"}
