### ISSUE TITLE
can't retrieve contact details

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#22]
merge of https://github.com/CaliOpen/caliopen.base.user/pull/6 make API GET /contacts/<uuid> fail on user_id validation

api_1           | 2016-04-22 15:48:44,730 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token
api_1           | 2016-04-22 15:48:44,734 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
api_1           | 2016-04-22 15:48:44,963 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/6a7ee4cf-e01b-4e34-a549-16ec6b78a5c1/contacts/_search [status:200 request:0.230s]
api_1           | No handlers could be found for logger "elasticsearch.trace"
api_1           | 2016-04-22 15:48:55,670 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token
api_1           | 2016-04-22 15:48:55,740 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/9f0383ef-2271-4fd6-9dfa-cbe71dcf0709
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 399, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1           |     response = view(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1           |     response = view_()
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 68, in get
api_1           |     return {'contacts': ReturnContact.build(contact).serialize()}
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/parameters.py", line 56, in build
api_1           |     obj.validate()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/schematics/models.py", line 262, in validate
api_1           |     raise ModelValidationError(exc.messages)
api_1           | ModelValidationError: {'user_id': [u'This field is required.']}
api_1           | 2016-04-22 15:49:23,488 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token
api_1           | 2016-04-22 15:50:03,309 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token
api_1           | 2016-04-22 15:50:03,389 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/9f0383ef-2271-4fd6-9dfa-cbe71dcf0709
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 399, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1           |     response = view(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1           |     response = view_()
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 68, in get
api_1           |     return {'contacts': ReturnContact.build(contact).serialize()}
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/parameters.py", line 56, in build
api_1           |     obj.validate()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/schematics/models.py", line 262, in validate
api_1           |     raise ModelValidationError(exc.messages)
api_1           | ModelValidationError: {'user_id': [u'This field is required.']}

**Comment by gdchamal** [comment]
fixed in last big merge
