### ISSUE TITLE
[smtp] unable to save an email from postfix (nor telnet direct connection)

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#24]
How to reproduce, 

* start lmtp bin on port `4444`
* use postfix with the following conf: 

```
postconf -e virtual_transport=lmtp:localhost:4444
postconf -e virtual_mailbox_domains=caliopen.local
```

* create a user: `dev@caliopen.local`

* start telnet and send a mail:

```
helo {client}
mail from: root@localhost
rcpt to: dev@caliopen.local
data
Subject: T2

foo

.
```
this produce the following log in postfix:

```
May  3 14:14:53 3950d9012669 postfix/master[1345]: reload -- version 2.11.3, configuration /etc/postfix
May  3 14:15:07 3950d9012669 postfix/smtpd[1402]: connect from localhost[::1]
May  3 14:15:14 3950d9012669 postfix/smtpd[1402]: disconnect from localhost[::1]
May  3 14:15:41 3950d9012669 postfix/smtpd[1402]: connect from localhost[::1]
May  3 14:16:13 3950d9012669 postfix/smtpd[1402]: 5FEE8C35: client=localhost[::1]
May  3 14:16:31 3950d9012669 postfix/cleanup[1408]: 5FEE8C35: message-id=<20160503141613.5FEE8C35@3950d9012669>
May  3 14:16:31 3950d9012669 postfix/qmgr[1400]: 5FEE8C35: from=<root@localhost>, size=307, nrcpt=1 (queue active)
May  3 14:16:37 3950d9012669 postfix/lmtp[1409]: 5FEE8C35: lost connection with localhost[127.0.0.1] while sending end of data -- message may be sent more than once
May  3 14:16:37 3950d9012669 postfix/lmtp[1409]: connect to localhost[::1]:4444: Connection refused
May  3 14:16:37 3950d9012669 postfix/lmtp[1409]: 5FEE8C35: to=<dev@caliopen.local>, relay=none, delay=35, delays=29/0/5.4/0, dsn=4.4.1, status=deferred (connect to localhost[::1]:4444: Connection refused)
May  3 14:17:46 3950d9012669 postfix/smtpd[1402]: disconnect from localhost[::1]
```

and the trace from lmtp daemon

```
gsmtpd:DEBUG:Peer: 127.0.0.1:47437
gsmtpd:DEBUG:Data: 'LHLO 3950d9012669\r\n'
gsmtpd:DEBUG:Data: 'MAIL FROM:<root@localhost>\r\n'
gsmtpd:DEBUG:===> MAIL FROM:<root@localhost>
gsmtpd:DEBUG:sender: root@localhost
gsmtpd:DEBUG:Data: 'RCPT TO:<dev@caliopen.local>\r\n'
gsmtpd:DEBUG:===> RCPT TO:<dev@caliopen.local>
gsmtpd:DEBUG:recips: ['dev@caliopen.local']
gsmtpd:DEBUG:Data: 'DATA\r\n'
gsmtpd:DEBUG:Data: 'Received: from 3950d9012669 (localhost [IPv6:::1])\r\n'
gsmtpd:DEBUG:Data: '\tby 3950d9012669 (Postfix) with SMTP id 5FEE8C35\r\n'
gsmtpd:DEBUG:Data: '\tfor <dev@caliopen.local>; Tue,  3 May 2016 14:16:02 +0000 (UTC)\r\n'
gsmtpd:DEBUG:Data: 'Subject: T2\r\n'
gsmtpd:DEBUG:Data: 'Message-Id: <20160503141613.5FEE8C35@3950d9012669>\r\n'
gsmtpd:DEBUG:Data: 'Date: Tue,  3 May 2016 14:16:02 +0000 (UTC)\r\n'
gsmtpd:DEBUG:Data: 'From: root@localhost\r\n'
gsmtpd:DEBUG:Data: '\r\n'
gsmtpd:DEBUG:Data: 'foo\r\n'
gsmtpd:DEBUG:Data: '.\r\n'
Traceback (most recent call last):                                                                                                                                                                        [108/133]
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gsmtpd/gsmtpd.py", line 65, in __init__
    self.chat()
  File "/usr/local/lib/python2.7/dist-packages/gsmtpd/gsmtpd.py", line 103, in chat
    "".join(body))
  File "caliopen/smtp/bin/lmtpd.py", line 28, in process_message
    messages = agent.process(mailfrom, rcpttos, data)
  File "/srv/caliopen/smtp/caliopen/smtp/agent.py", line 64, in process
    users = self.resolve_users(rcpts)
  File "/srv/caliopen/smtp/caliopen/smtp/agent.py", line 45, in resolve_users
    user = User.by_name(rcpt)
  File "/srv/caliopen/src/caliopen.base.user/caliopen/base/user/core/user.py", line 158, in by_name
    uname = UserName.get(name.lower())
  File "/srv/caliopen/src/caliopen.base/caliopen/base/core/base.py", line 69, in get
    obj = cls._model_class.get(**params)
  File "/srv/caliopen/src/caliopen.base/caliopen/base/store/model.py", line 37, in get
    return super(BaseModel, cls).get(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/models.py", line 651, in get
    return cls.objects.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 666, in get
    return self.filter(*args, **kwargs).get()
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 668, in get
    self._execute_query()
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 386, in _execute_query
    self._result_generator = (i for i in self._execute(self._select_query()))
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 318, in _execute
    result = _execute_statement(self.model, statement, self._consistency, self._timeout)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1353, in _execute_statement
    parts = model._routing_key_from_values(key_values, connection.get_cluster().protocol_version)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/connection.py", line 183, in get_cluster
    raise CQLEngineException("%s.cluster is not configured. Call one of the setup or default functions first." % __name__)
CQLEngineException: cassandra.cqlengine.connection.cluster is not configured. Call one of the setup or default functions first.
<Greenlet at 0x7f49c546c910: _handle_and_close_when_done(<functools.partial object at 0x7f49c5483f70>, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f49c5490990 fileno=[Errno 9] Bad fi)> fai
led with CQLEngineException
```

**Comment by gdchamal** [comment]
This commit permit to ignore if no Date header found and permit to have a better debug status during mail parsing:

https://github.com/CaliOpen/caliopen.base.message/commit/3c3ca9a4b28fb6837016b6fccc95fdc91817615f
