### ISSUE TITLE
load fixtures with filename in utf-8 don't work in docker container

### ISSUE THREAD

**Issue by gdchamal** [CaliOpen/Caliopen#29]
Using a default docker configuration, when loading fixtures got python encode error on some filenames.

It appear that file with an utf-8 name can't be imported. They are seen with a different encoding in the container.

(venv) tao~/dev/caliopen/bin/fixtures/dev@caliopen.local/mbox(features/index-mapping|✚1…) % ls -l [Caliopdev]\ CR*
-rw-r--r-- 1 mric mric 13791 31 mai   18:08 '[Caliopdev] CR réunion du 12_12_2014 - Thomas Laurent thomas.laurent@gandi.net - 2014-12-12 1701.eml'

(venv) tao~/dev/caliopen/bin(features/index-mapping|✚1…) % docker-compose run cli /bin/bash
root@b406c0202b3f:/srv/caliopen/cli# cd /usr/share/caliopen/bin/fixtures/dev\@caliopen.local/mbox/
root@b406c0202b3f:/usr/share/caliopen/bin/fixtures/dev@caliopen.local/mbox# ls -l [Caliopdev]\ CR*
-rw-r--r-- 1 docker docker 13791 May 31 16:08 [Caliopdev] CR r??union du 12_12_2014 - Thomas Laurent thomas.laurent@gandi.net - 2014-12-12 1701.eml

run of load-fixtures with some debug:
###### ###################### u'1460463563.5266_205.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463563.5266_205.argentina:2,
###### ###################### u'1460463569.5266_635.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463569.5266_635.argentina:2,
###### ###################### u'1460463567.5266_493.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463567.5266_493.argentina:2,
###### ###################### u'1460463564.5266_315.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463564.5266_315.argentina:2,
###### ###################### u'1460463565.5266_403.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463565.5266_403.argentina:2,
###### ###################### u'1460463566.5266_469.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463566.5266_469.argentina:2,
###### ###################### u'1460463564.5266_325.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463564.5266_325.argentina:2,
###### ###################### u'1460463569.5266_665.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463569.5266_665.argentina:2,
###### ###################### u'1460463561.5266_41.argentina:2,'

DEBUG:caliopen.cli.commands.import_email:Importing mail from file 1460463561.5266_41.argentina:2,
###### ###################### 'Re: [Caliopdev] Prochaine r\xc3\xa9union - David Epely dey@protonmail.ch - 2014-12-02 1056.eml'

Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/srv/caliopen/cli/caliopen/cli/cli.py", line 66, in main
    func(**kwargs)
  File "/srv/caliopen/cli/caliopen/cli/commands/import_email.py", line 43, in import_email
    os_file = f.encode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)

**Comment by gdchamal** [comment]
maybe an open problem for docker, no more for us.
