### ISSUE TITLE
Catch unicity exception for contact details

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#30]
a readable error should be rendered: 

POST data in emails

```
2016-07-21 13:03:32,010 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/a516b874-2dc3-4eef-8c34-3bba9ddadeb6/emails
api_1 | Traceback (most recent call last):
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-1.0a2-py2.7.egg/waitress/channel.py", line 338, in service
api_1 |     task.service()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-1.0a2-py2.7.egg/waitress/task.py", line 169, in service
api_1 |     self.execute()
api_1 |   File "/usr/local/lib/python2.7/dist-packages/waitress-1.0a2-py2.7.egg/waitress/task.py", line 399, in execute
api_1 |     app_iter = self.channel.server.application(env, start_response)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1 |     response = self.invoke_subrequest(request, use_tweens=True)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1 |     response = handle_request(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1 |     response = view_callable(exc, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1 |     result = view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1 |     response = handler(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1 |     response = view_callable(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1 |     return view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1 |     result = view(context, request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1 |     response = view(request)
api_1 |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1 |     response = view_()
api_1 |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 231, in collection_post
api_1 |     return self._create(email, 'add_email', ReturnEmail)
api_1 |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 136, in _create
api_1 |     nested = func(params)
api_1 |   File "/srv/caliopen/src/caliopen.base.user/caliopen/base/user/core/contact.py", line 271, in add_email
api_1 |     return self._add_nested('emails', email)
api_1 |   File "/srv/caliopen/src/caliopen.base.user/caliopen/base/user/core/contact.py", line 88, in _add_nested
api_1 |     raise Exception('Unicity conflict for {}'.format(uniq))
api_1 | Exception: Unicity conflict for foo@bar.tld
```

**Comment by gdchamal** [comment]
Yes I matter to fix that point soon, as I introduce this new check during index layer rework.

What do you expect on client side for such error ?

**Comment by gdchamal** [comment]
not valid anymore, backend code and email structure as in this issue completly rewritten
