### ISSUE TITLE
contacts are not synced fastly enough after imports

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#321]
I can successfuly POST a new draft then fetch it:

```
// request
POST http://localhost:4000/api/v1/messages
{
	"participants": [],
	"body": "foo",
	"identities": [{
		"display_name": "None None",
		"identifier": "dev@caliopen.local",
		"status": "active",
		"type": "email",
		"user_id": "ae5c0c9d-163a-4600-be10-751e9e2bcb23"
	}]
}
//response 
status 200
{"location": "/api/v1/messages/606dfdb8-f3e3-4dc0-9ded-2fc76ed32285"}

//request
GET  http://localhost:4000/api/v1/messages/606dfdb8-f3e3-4dc0-9ded-2fc76ed32285
// response
status 200
{
	"body": "foo",
	"identities": [{
		"status": null,
		"type": "email",
		"identifier": "dev@caliopen.local",
		"display_name": null,
		"user_id": null
	}],
	"date_insert": "2017-05-23T15:40:34.407000+00:00",
	"participants": [{
		"protocol": "email",
		"type": "From",
		"label": "None None",
		"contact_ids": ["868f6e24-3811-44d1-9294-874a62565f3e"],
		"address": "dev@caliopen.local"
	}],
	"discussion_id": "da46cc34-aa83-4ce5-bfb5-384b56175326",
	"type": "email",
	"is_draft": true,
	"message_id": "606dfdb8-f3e3-4dc0-9ded-2fc76ed32285"
}
```

I now have the discussion_id but I can fetch it:

```
// request
GET http://localhost:4000/api/v1/discussions/da46cc34-aa83-4ce5-bfb5-384b56175326
// response
status 404
{
	"errors": [{
		"code": 404,
		"description": "The resource could not be found.",
		"component": "discussion",
		"values": 404,
		"message": "No such discussion u'da46cc34-aa83-4ce5-bfb5-384b56175326'",
		"property": "ResourceNotFound",
		"type": "Not Found"
	}]
}
```

**Comment by iamdey** [comment]
btw the message list by discussion_id also fails

```
GET http://localhost:4000/api/v1/messages?offset=0&limit=20&discussion_id=da46cc34-aa83-4ce5-bfb5-384b56175326
{"errors": [{"code": 404, "description": "The resource could not be found.", "component": "collection_message", "values": 404, "message": "None", "property": "ResourceNotFound", "type": "Not Found"}]}
```

**Comment by sapiens-sapide** [comment]
I cannot reproduce these issues in my environment, neither in a brand new docker stack (from a brand new `git clone` in master)…

**Comment by iamdey** [comment]
#cmcm :D 

Well, I think the problem is that I try to fetch the discussion *too fast*.

First screenshot I POST a new draft then fetch all the thing (the discussion and the messages of the discussion) and so it fails.

![capture d ecran de 2017-05-30 14-19-34](https://cloud.githubusercontent.com/assets/65737/26583019/aeb21e96-4543-11e7-9b51-a307305662af.png)

but if I refresh (same requests except the POST), it works:

![capture d ecran de 2017-05-30 14-20-42](https://cloud.githubusercontent.com/assets/65737/26583051/de5979a0-4543-11e7-92a3-277ab67e819a.png)

**Comment by sapiens-sapide** [comment]
Could you provide us with errors details ? Thks.

**Comment by iamdey** [comment]
Ok so when I don't slow down the server I have those errors:*

I'm not sure this one is related (save first draft):

```
cassandra_1        | INFO  2017-05-31 09:19:00,652 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-28-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-32-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-24-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-20-Data.db:level=0, ]
cassandra_1        | INFO  2017-05-31 09:19:00,872 [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-40-Data.db:level=0, ]. 13408 bytes to 12649 (~94% of original) in 220ms = 0.0548319MB/s. ~1024 total partitions merged to 1.
cassandra_1        | INFO  2017-05-31 09:19:00,873 [shard 0] storage_service - Node 172.20.0.4 state jump to normal
cassandra_1        | INFO  2017-05-31 09:19:01,065 [shard 0] storage_service - NORMAL: node is now in normal status
cassandra_1        | INFO  2017-05-31 09:19:01,071 [shard 0] gossip - Feature RANGE_TOMBSTONES is enabled
cassandra_1        | INFO  2017-05-31 09:19:01,071 [shard 0] gossip - Feature LARGE_PARTITIONS is enabled
cassandra_1        | INFO  2017-05-31 09:19:01,072 [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
cassandra_1        | INFO  2017-05-31 09:19:09,072 [shard 0] gossip - No gossip backlog; proceeding
cassandra_1        | INFO  2017-05-31 09:19:09,077 [shard 0] storage_service - Starting listening for CQL clients on 172.20.0.4:9042...
cassandra_1        | INFO  2017-05-31 09:19:09,078 [shard 0] storage_service - Thrift server listening on 172.20.0.4:9160 ...
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/message/discussion.py", line 48, in get
apiv1_1            |     resp = build_discussion(discussion, indexed_discussion)
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/discussion/core/discussion.py", line 63, in build_discussion
apiv1_1            |     discuss.date_update = index.last_message.date_insert
apiv1_1            |  AttributeError: 'NoneType' object has no attribute 'last_message'
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 261
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            | 
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "discussion", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
apiv1_1            | 2017-05-31 09:30:31,498 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
apiv1_1            | 2017-05-31 09:30:31,503 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/_search [status:200 request:0.005s]
apiv1_1            | 2017-05-31 09:30:31,509 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/_search [status:200 request:0.005s]
```

And this one on another save:

```
apiv1_1            | 2017-05-31 09:31:36,730 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
apiv1_1            | 2017-05-31 09:31:36,768 INFO  [elasticsearch][waitress] PUT http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/635beb3b-5cff-43e4-a35b-d922baea3b0b [status$
201 request:0.038s]
apiv1_1            | 2017-05-31 09:31:36,973 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
apiv1_1            | 2017-05-31 09:31:36,979 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/_search [status:200 request:0.007s]
apiv1_1            | 2017-05-31 09:31:36,982 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/message/discussion.py", line 48, in get
apiv1_1            |     resp = build_discussion(discussion, indexed_discussion)
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/discussion/core/discussion.py", line 63, in build_discussion
apiv1_1            |     discuss.date_update = index.last_message.date_insert
apiv1_1            |  AttributeError: 'NoneType' object has no attribute 'last_message'
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 261
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            | 
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "discussion", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
apiv1_1            | 2017-05-31 09:31:37,025 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
apiv1_1            | 2017-05-31 09:31:37,042 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/_search [status:200 request:0.017s]
apiv1_1            | 2017-05-31 09:31:37,043 WARNI [caliopen_api.message.message][waitress] 
apiv1_1            | 2017-05-31 09:31:37,071 INFO  [urllib3.connectionpool][waitress] Starting new HTTP connection (1): es.dev.caliopen.org
apiv1_1            | 2017-05-31 09:31:37,082 INFO  [elasticsearch][waitress] GET http://es.dev.caliopen.org:9200/ec321903-1e23-4c6c-9879-6a5af17fbded/indexed_message/_search [status:200 request:0.011s]
apiv1_1            | 2017-05-31 09:31:37,085 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/message/discussion.py", line 48, in get
apiv1_1            |     resp = build_discussion(discussion, indexed_discussion)
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/discussion/core/discussion.py", line 63, in build_discussion
apiv1_1            |     discuss.date_update = index.last_message.date_insert
apiv1_1            |  AttributeError: 'NoneType' object has no attribute 'last_message'
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 261
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            | 
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "discussion", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
```

**Comment by sapiens-sapide** [comment]
The issue comes from ElasticSearch behavior : there is a delay between the `PUT` of a document in ES and the moment this document is visible for searches.  
We have no way to know when a document is actually visible with ES engine 2.4, the engine version we currently use.  

But, this issue could be overcame with ES engine 5. We'll see with @gdchamal if we can change ES engine to version 5+.

**Comment by sapiens-sapide** [comment]
As we moved the stack to ES 5 engine, could @iamdey tell us if the issue is still ? (We may have to change ES settings).
Thanks.

**Comment by iamdey** [comment]
it looks goo

**Comment by iamdey** [comment]
I think there's some tunes to do:

when I import contacts, I fetch contacts after successful upload but the list is not up to date.

(Then I refresh several seconds later and got ERR500 but it's not related, I think in normal operation it is correct)

**Comment by iamdey** [comment]
the ERR is fixed but the collection is not up to date quick enough:

![sync contacts](https://user-images.githubusercontent.com/65737/28680029-5c148874-72f5-11e7-9355-f1991dfcb535.png)

You'll see a status 304 just after the imports request in timeline

**Comment by iamdey** [comment]
up /cc @sapiens-sapide

**Comment by sapiens-sapide** [comment]
We will not change this but will change how the API work :  

It will not respond anymore with `200` code on `POST` and `PATCH` verbs. You will have a `202 Accepted` response if the request went well. It will the responsability of the frontend to manage retries & timeout if it doesn't get the desired ressource immediately.  

Need to write a story to apply these changes on the whole stack.

**Comment by iamdey** [comment]
I add an entry in todo #424
