### ISSUE TITLE
ERR 500 api/v1/imports

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#343]
```
apiv1_1            | 2017-06-14 12:52:58,762 WARNI [caliopen_api.user.authentication][waitress] No X-Caliopen-PI header
apiv1_1            | 2017-06-14 12:52:58,762 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/user/imports.py", line 36, in collection_post
apiv1_1            |     log.error('File valid but we can create the new contact: {}'.format(exc))
apiv1_1            |  NameError: global name 'log' is not defined
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 275
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            | 
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "collection_contactimport", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
```

**Comment by iamdey** [comment]
fixed in #332
