### ISSUE TITLE
Patch contact

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#364]
ERR 400 on contact PATCH

* [ ] missing id
* [ ] additional params

---

missing id : Emails / addresses:

request payload:
```
{
	"current_state": {
		"emails": [{
			"email_id": "d56b19de-3e11-4c19-8a63-fa7224915a4f",
			"is_primary": false,
			"type": "other",
			"address": "alan@idiocy.org"
		}]
	},
	"emails": [{
		"email_id": "d56b19de-3e11-4c19-8a63-fa7224915a4f",
		"is_primary": false,
		"type": "other",
		"address": "alan@idiocy.org"
	}, {
		"address": "aazd@azdkh",
		"type": "work",
		"is_primary": false
	}]
}
```

response:

```
{
	"errors": [{
		"code": 400,
		"description": "The server could not comply with the request since it is either malformed or otherwise incorrect.",
		"component": "Unknown",
		"values": 400,
		"message": "u'email_id' is a required property\n\nFailed validating u'required' in schema[u'properties'][u'emails'][u'items']:\n    {u'additionalProperties': False,\n     u'properties': {u'address': {u'type': u'string'},\n                     u'email_id': {u'type': u'string'},\n                     u'is_primary': {u'type': u'boolean'},\n                     u'label': {u'type': u'string'},\n                     u'type': {u'type': u'string'}},\n     u'required': [u'email_id', u'address'],\n     u'type': u'object'}\n\nOn instance[u'emails'][1]:\n    {u'address': u'aazd@azdkh', u'is_primary': False, u'type': u'work'}",
		"property": "RequestValidationError",
		"type": "Bad Request"
	}]
}
```

**Comment by iamdey** [comment]
Phones:

request payload:

```
{
	"current_state": {},
	"phones": [{
		"number": "654",
		"type": "work",
		"is_primary": false
	}]
}
```

response:

```
{
	"errors": [{
		"code": 400,
		"description": "The server could not comply with the request since it is either malformed or otherwise incorrect.",
		"component": "Unknown",
		"values": 400,
		"message": "Additional properties are not allowed (u'is_primary', u'type', u'number' were unexpected)\n\nFailed validating u'additionalProperties' in schema[u'properties'][u'phones'][u'items'][u'allOf'][1]:\n    {u'additionalProperties': False,\n     u'properties': {u'phone_id': {u'type': u'string'}},\n     u'required': [u'phone_id'],\n     u'type': u'object'}\n\nOn instance[u'phones'][0]:\n    {u'is_primary': False, u'number': u'654', u'type': u'work'}",
		"property": "RequestValidationError",
		"type": "Bad Request"
	}]
}
```

**Comment by sapiens-sapide** [comment]
Should be OK now with `"current_state": {}` or `"current_state":{"<property>": []}`

**Comment by iamdey** [comment]
I've a 409 on an imported contact:

request:

```
{
	"current_state": {},
	"identities": [{
		"type": "twitter",
		"name": "@azd"
	}]
}
```

response:

```
{
	"errors": [{
		"code": 409,
		"description": "The request cannot be applied given the state of the resource",
		"component": "contact",
		"values": 409,
		"message": "Patch current_state not consistent with db, step 0 key identities",
		"property": "MergePatchError",
		"type": "Patch Conflict"
	}]
}
```

**Comment by iamdey** [comment]
* email, phone, im: **OK**
* address, organization : **KO**

err 409 on organizations, it fails when adding a second orga:
req:

```
{
	"current_state": {
		"organizations": [{
			"name": "bar",
			"title": "",
			"deleted": false,
			"is_primary": false,
			"label": "foo",
			"organization_id": "72c02f72-211d-40c6-8321-76582d608816",
			"job_description": "",
			"department": ""
		}]
	},
	"organizations": [{
		"name": "bar",
		"title": "",
		"deleted": false,
		"is_primary": false,
		"label": "foo",
		"organization_id": "72c02f72-211d-40c6-8321-76582d608816",
		"job_description": "",
		"department": ""
	}, {
		"department": "",
		"is_primary": false,
		"job_description": "",
		"label": "one",
		"name": "onone",
		"title": ""
	}]
}
```

resp:

```
{
	"errors": [{
		"code": 409,
		"description": "The request cannot be applied given the state of the resource",
		"component": "contact",
		"values": 409,
		"message": "Patch current_state not consistent with db, step 3 key organizations",
		"property": "MergePatchError",
		"type": "Patch Conflict"
	}]
}
```

**Comment by sapiens-sapide** [comment]
Should be fixed by commit #1c429b2

**Comment by iamdey** [comment]
new error:

When trying to patch the contact related to the user:

PATCH /contacts/<id>

```
{
	"current_state": {
		"title": ""
	},
	"title": "DEV",
	"infos": {
		"birthday": ""
	}
}
```

resp:

```
{"errors": [{"code": 409, "description": "The request cannot be applied given the state of the resource", "component": "contact", "values": 409, "message": "Patch current_state not consistent with db, step 5 key infos", "property": "MergePatchError", "type": "Patch Conflict"}]}
```

**Comment by iamdey** [comment]
Other Pbm,  Patch new phone, not taken in account:

req PATH 204 (ok)

```
{
	"current_state": {},
	"phones": [{
		"number": "+33654321000",
		"type": "work",
		"is_primary": false
	}]
}
```

GET 304 (not ok, it should be 200)

```
{
	"family_name": "dey",
	"user_id": "95827170-d571-431e-95b9-efe7c315f0a3",
	"title": "dey",
	"additional_name": "",
	"name_suffix": "",
	"contact_id": "ac8de8cf-ba2e-4d85-aaf6-44dbf3a95cfe",
	"date_insert": "2017-07-07T09:04:05.950000+00:00",
	"deleted": false,
	"given_name": "",
	"name_prefix": "",
	"emails": [{
		"email_id": "65557c00-0692-4887-ba17-9ce0f228e207",
		"is_primary": false,
		"label": "",
		"type": "other",
		"address": "dey@protonmail.ch"
	}, {
		"is_primary": false,
		"label": "",
		"type": "work",
		"address": "dey@inbucket.local"
	}],
	"avatar": ""
}
```

notice:

* the expected phone is missing
* the second email address has no email_id (but I don't care for now) 
* I think it's strange that a contact has a user_id (only the user should have a contact_id in standard db design)

**Comment by iamdey** [comment]
and then contact list is fouktup

req GET http://localhost:4000/api/v1/contacts?offset=0&limit=1000 ERR500:

```
apiv1_1            | 2017-07-07 10:55:11,093 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/user/contact.py", line 55, in collection_get
apiv1_1            |     serialize() for x in results]
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.storage/caliopen_storage/parameters.py", line 90, in build
apiv1_1            |     obj.validate()
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/models.py", line 254, in validate
apiv1_1            |     partial=partial, convert=convert, app_data=app_data, **kwargs)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/models.py", line 295, in _convert
apiv1_1            |     return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/validate.py", line 65, in validate
apiv1_1            |     raise DataError(errors, data)
apiv1_1            |  DataError: {"organizations": {"0": {"type": ["Value must be one of [u'work', u'home']."]}}, "phones": {"0": {"uri": ["Not a well-formed URL."]}}}
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 269
apiv1_1            | Content-Type: application/json; charset=UTF-8
```

**Comment by sapiens-sapide** [comment]
Please checkout the two last issues after commits #9f13c52 and #8f1237b.

**Comment by iamdey** [comment]
All works as expected
