### ISSUE TITLE
RemoteIdentityAPI: error 500

### ISSUE THREAD

**Issue by lisonferez** [CaliOpen/Caliopen#383]
2017-07-03 11:05:15,571 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
   File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
    response = handler(request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 362, in rendered_view
    response = registry.queryAdapterOrSelf(result, IResponse)
   File "/home/lison/caliopen/src/github.com/CaliOpen/Caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.8-py2.7.egg/pyramid/registry.py", line 62, in queryAdapterOrSelf
    if not interface.providedBy(object):
 TypeError: 'NoneType' object is not callable
: 500 Internal Server Error
Content-Length: 278
Content-Type: application/json; charset=UTF-8

{"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "collection_RemoteIdentities", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}

**Comment by gdchamal** [comment]
can you provide also the related API call that trigger this error ?

**Comment by lisonferez** [comment]
/v1/identities/remotes

**Comment by gdchamal** [comment]
The return object is not correctly formatted. Currently the core RemoteIdentity is returned by the API, it's wrong design, my bad.

Will try to fix this quickly, but need introduction of new API (upon POST we must reply with A 201 HTTP code and a Location header to be use for a GET /resources/<id> not existing for remote identity)

**Comment by gdchamal** [comment]
fix done
