### ISSUE TITLE
draft form is missing 

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#537]
```
app.507a7aa4b60b8c665eab.js:16 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at P (https://alpha.caliopen.org/assets/app.507a7aa4b60b8c665eab.js:16:7428)
    at https://alpha.caliopen.org/assets/app.507a7aa4b60b8c665eab.js:16:5505
    at r (https://alpha.caliopen.org/assets/vendor.49e775c1b8dce1f0164a.js:104:3059)
    at Generator._invoke (https://alpha.caliopen.org/assets/vendor.49e775c1b8dce1f0164a.js:104:4179)
    at Generator.t.(anonymous function) [as next] (https://alpha.caliopen.org/assets/vendor.49e775c1b8dce1f0164a.js:104:3238)
    at r (https://alpha.caliopen.org/assets/app.507a7aa4b60b8c665eab.js:16:4255)
    at https://alpha.caliopen.org/assets/app.507a7aa4b60b8c665eab.js:16:4355
    at <anonymous>
```

```js
n=e.user
// ...
o=n.contact.emails
i=o.map(function(e){return e.address})
// ...
```

this mean the user is **not** attached to a contact

**Comment by iamdey** [comment]
more precisely, the email auto-generated for the user is not attached to the user: so the property `user.contact.emails` is undefined

**Comment by sapiens-sapide** [comment]
Should we add `recovery_email` and `given_name` to the Contact created ? @iamdey @gdchamal

**Comment by iamdey** [comment]
Yes

Le jeu. 19 oct. 2017 16:34, Stanislas SABATIER <notifications@github.com> a
écrit :
