### ISSUE TITLE
Patch on  settings "contact_display_format" returns 500

### ISSUE THREAD

**Issue by myleneb** [CaliOpen/Caliopen#543]
When you try to update "contact_display_format" in settings, it returns:
```
{"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "Settings", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
```

**Comment by iamdey** [comment]
```
piv1_1            | 2017-10-20 08:48:26,983 WARNI [caliopen_main.common.objects.base][waitress] document validation failed with error {"contact_display_format": ["Value must be one of [u'given_name', u'family_n
ame', u'family_name, given_name']."]}               
apiv1_1            | 2017-10-20 08:48:26,984 INFO  [caliopen_main.common.objects.base][waitress] {"contact_display_format": ["Value must be one of [u'given_name', u'family_name', u'family_name, given_name']."]}
apiv1_1            | 2017-10-20 08:48:26,996 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 187, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/user/settings.py", line 53, in patch
apiv1_1            |     error = settings.apply_patch(patch, db=True)
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/common/objects/base.py", line 344, in apply_patch
apiv1_1            |     exc))
apiv1_1            |  PatchUnprocessable: unable to unmarshall patch into object <{"contact_display_format": ["Value must be one of [u'given_name', u'family_name', u'family_name, given_name']."]}>
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 259
apiv1_1            | Content-Type: application/json; charset=UTF-8
```
