### ISSUE TITLE
err 500 local/indenties sometimes

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#618]
GET https://alpha.caliopen.org/api/v2/identities/locals

Err 500

```
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:573:10)
    at ServerResponse.send (/opt/caliopen/client.0.5.4/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/opt/caliopen/client.0.5.4/node_modules/express/lib/response.js:267:15)
    at catchError (/opt/caliopen/client.0.5.4/dist/server/index.js:52353:28)
    at Layer.handle_error (/opt/caliopen/client.0.5.4/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/caliopen/client.0.5.4/node_modules/express/lib/router/index.js:315:13)
    at /opt/caliopen/client.0.5.4/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/caliopen/client.0.5.4/node_modules/express/lib/router/index.js:335:12)
```

after a refresh it's ok

**Comment by iamdey** [comment]
no more reproducible
