### ISSUE TITLE
unable to inject mail in docker dev env

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#885]
* Following the documentation:

```bash
docker-compose run cli inject -r dev@caliopen.local -e devtools/fixtures/raw_emails/multipart-html

usage: caliopen [-h] [-f CONFFILE]
                {import,import_vcard,setup,create_user,shell,set_notifs_ttls,dump,dump_index,migrate_index,inject,compute,reserved_names}
                ...
caliopen: error: unrecognized arguments: -r dev@caliopen.local
```

* without -r:

```
docker-compose run cli inject -e devtools/fixtures/raw_emails/multipart-html
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 11, in <module>
    load_entry_point('caliopen-cli', 'console_scripts', 'caliopen')()
  File "/srv/caliopen/src/backend/tools/py.CLI/caliopen_cli/cli.py", line 108, in main
    func(**kwargs)
  File "/srv/caliopen/src/backend/tools/py.CLI/caliopen_cli/commands/inject_email.py", line 28, in inject_email
    if os.path.isdir(import_path):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

* same error using an other raw_email

**Comment by gdchamal** [comment]
Can't reproduce issue with a fresh stack and build of cli

**Comment by iamdey** [comment]
after a full rebuild it lloks ok
