### ISSUE TITLE
unable to load fixtures

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#886]
```bash
docker-compose run cli import -e dev@caliopen.local -f mbox -p devtools/fixtures/mbox/dev@caliopen.local
```

```
ERROR:caliopen_cli.commands.import_email:Error importing email 'ascii' codec can't decode byte 0xc3 in position 1554: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 11, in <module>
    load_entry_point('caliopen-cli', 'console_scripts', 'caliopen')()
  File "/srv/caliopen/src/backend/tools/py.CLI/caliopen_cli/cli.py", line 105, in main
    func(**kwargs)
  File "/srv/caliopen/src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py", line 65, in import_email
    user = User.by_local_identity(dest_email)
  File "/srv/caliopen/src/backend/main/py.main/caliopen_main/user/core/user.py", line 350, in by_local_identity
    identity = LocalIdentity.get(address.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by gdchamal** [comment]
fixed with #f2fcc431
