### ISSUE TITLE
unable to login on android

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#917]
unable to login on FF or chrome for android

**Comment by iamdey** [comment]
it looks like it's an error from apiv1:


```
apiv1_1            | 2018-05-14 13:53:05,482 INFO  [caliopen_api.user.user][waitress] Authenticate user dev
apiv1_1            | 2018-05-14 13:53:05,488 WARNI [caliopen_pi.features.device][waitress] Invalid geoip2 file configuration
apiv1_1            | 2018-05-14 13:53:05,496 ERROR [caliopen_api.base.errors][waitress] Unexpected error Traceback (most recent call last):
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/pyramid_swagger/tween.py", line 193, in validator_tween
apiv1_1            |     response = handler(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
apiv1_1            |     response = view_callable(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
apiv1_1            |     return view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
apiv1_1            |     result = view(context, request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
apiv1_1            |     response = view(request)
apiv1_1            |    File "/usr/local/lib/python2.7/dist-packages/cornice-1.2.1-py2.7.egg/cornice/service.py", line 571, in wrapper
apiv1_1            |     response = view_()
apiv1_1            |    File "/srv/caliopen/src/backend/interfaces/REST/py.server/caliopen_api/user/user.py", line 71, in collection_post
apiv1_1            |     self.request.headers)
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/device/core.py", line 79, in create_from_parameter
apiv1_1            |     return Device.create(user, dev, public_keys=[dev_key])
apiv1_1            |    File "/srv/caliopen/src/backend/main/py.main/caliopen_main/device/core.py", line 84, in create
apiv1_1            |     device.validate()
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/models.py", line 254, in validate
apiv1_1            |     partial=partial, convert=convert, app_data=app_data, **kwargs)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/models.py", line 295, in _convert
apiv1_1            |     return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
apiv1_1            |    File "build/bdist.linux-x86_64/egg/schematics/validate.py", line 65, in validate
apiv1_1            |     raise DataError(errors, data)
apiv1_1            |  DataError: {"type": ["Value must be one of [u'other', u'desktop', u'laptop', u'smartphone', u'tablet']."]}
apiv1_1            | : 500 Internal Server Error
apiv1_1            | Content-Length: 276
apiv1_1            | Content-Type: application/json; charset=UTF-8
apiv1_1            | 
apiv1_1            | {"errors": [{"code": 500, "description": "The server has either erred or is incapable of performing the requested operation.", "component": "collection_Authentication", "values": 500, "message": "None", "property": "HTTPInternalServerError", "type": "Internal Server Error"}]}
```
